### ISSUE TITLE
Time Benchmark

### ISSUE THREAD

**Issue by DonaldTsang** [grandchild/base32k#1]
Requesting comparison between this and http://blog.kevinalbs.com/base122 and http://base91.sourceforge.net/

**Comment by grandchild** [comment]
I don't think this is useful. Base122 is a library in Javascript, a language with a very different domain than Go, and a comparison is likely not useful. Base91 is in Assembly/C and it might be useful, if not for the second point:

This project does not serve well as a compact data transmission method, except for those rare situations where the limit is characters not bytes. And even then, [base2048](https://github.com/qntm/base2048) (which I discovered after I did this) is a way better fit.

**Comment by DonaldTsang** [comment]
@grandchild understood.
